version: '3.3'
services:
  openweatherproxy:
    restart: unless-stopped
    container_name: owp
    env_file: .env
    ports:
      - ${DOCKER_EXPOSED_PORT}:${OWP_PORT}
    image: pans0n/openweatherproxy
